name: Update .pre-commit-config.yaml

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.16.2"

jobs:
  update-pre-commit-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.14'

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update .pre-commit-config.yaml
        run: hatch run pre-commit autoupdate --freeze

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "chore(deps): Update .pre-commit-config.yaml"
          title: "chore(deps): Update .pre-commit-config.yaml"
          body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
          branch: "update/pre-commit-config-yaml"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
